# Generated by Django 5.0.4 on 2024-04-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
