# Generated by Django 5.0.4 on 2024-04-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_updateTodoAppTableTitleValue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoapp',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
